
services:
  proyecto-final-frontend:
    image: proyecto-final-frontend
    build:
      context: ./Delivery-frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000