# Generated by Django 4.2.16 on 2024-10-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
