# Generated by Django 4.2.16 on 2024-10-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0002_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
