# Generated by Django 4.2.16 on 2024-10-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0003_pedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
