# Generated by Django 4.2.16 on 2024-10-22 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0004_pedido_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(default='XXXXXXX', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener exactamente 7 caracteres alfanuméricos.', regex='^[A-Za-z0-9]{7}$')]),
            preserve_default=False,
        ),
    ]
