# Generated by Django 4.2.16 on 2024-10-30 19:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0006_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='coordenadas_destino',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='pedido',
            name='coordenadas_origen',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='ruta',
            name='ruta_geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
