# Generated by Django 4.2.16 on 2024-11-04 13:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0007_pedido_coordenadas_destino_pedido_coordenadas_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('punto_origen', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
