# Generated by Django 4.2.16 on 2024-11-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0008_configuracion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], max_length=50),
        ),
    ]
