# Generated by Django 4.2.16 on 2024-11-14 20:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0010_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ubicacion_geografica',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
