# Generated by Django 4.2.16 on 2024-11-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0011_alter_vehiculo_ubicacion_geografica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AngusEats.conductor'),
        ),
    ]
