# Generated by Django 4.2.16 on 2024-11-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0012_pedido_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ruta',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
