# Generated by Django 4.2.16 on 2024-11-24 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0015_ubicacion_remove_pedido_coordenadas_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='ubicacion_geografica',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='AngusEats.ubicacion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='AngusEats.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('conductor', 'Conductor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='AngusEats.usuario'),
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
    ]
