# Generated by Django 5.1.6 on 2025-03-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0017_remove_usuario_contrasena_hash_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisispedido',
            name='pedidos_cancelados',
            field=models.IntegerField(default=0),
        ),
    ]
