# Generated by Django 5.1.6 on 2025-03-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AngusEats', '0018_analisispedido_pedidos_cancelados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialGPS',
        ),
    ]
